### ISSUE TITLE
[BUG]；在类网页应用的编辑框粘贴刚复制的内容时，无法及时粘贴或粘贴之前复制的内容。

### ISSUE THREAD

**Issue by hwf1324** [cary-rowen/clipboardEnhancement#13]
## 复现步骤：

1. 复制一段文本
2. 在此Issue的评论编辑框粘贴

## 实际行为：

按多次`Ctrl+V`都无法粘贴，不管是刚复制的内容还是之前复制的历史内容。
过一段时间后有可能会粘贴上次复制的内容。
过一段时间成功粘贴刚复制的内容。

## 预期行为：

始终可以粘贴内容。

## 操作系统：

Windows 11
版本 22H2 (OS 内部版本 22621.3007)

## NVDA 版本：

2023.3.2 便携版
只安装了剪贴板增强 2.8.0

## 其它信息：

在未使用此插件时正常

**Comment by cary-rowen** [comment]
暂未复现，禁用其他插件是否依然能够复现。

**Comment by hwf1324** [comment]
可以，我在2023.2的便携版上只安装此插件测试。这也许跟剪贴板监视器或系统有关？

**Comment by cary-rowen** [comment]
有可能存在系统环境差异。

**Comment by lylc0000** [comment]
在我这里也没有重现，看来这排查起来很麻烦了。
按理说ctrl加v应该和本插件无关才对，毕竟这是系统的粘贴热键。

**Comment by hwf1324** [comment]
目前无法复现，关闭此 Issue。
